# Order is respected upon duplicates.
"urn:oid:2.5.4.42": "first_name"
"urn:oid:2.5.4.4": "last_name"
"urn:oid:2.16.840.1.113730.3.1.241": "last_name"
"urn:oid:0.9.2342.19200300.100.1.3": "email"
"urn:oid:0.9.2342.19200300.100.1.1": "username"
"urn:oid:1.3.6.1.4.1.5923.1.1.1.6": "username"
