# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Secret keys are stored in config/keys.yml
# and read into the global variable SECRET_KEYS
# when the application is started (in config/application.rb)

development:
  secret_key_base: <%= SECRET_KEYS['secret_key_base'] %>
  smartschool_client_id: <%= SECRET_KEYS['smartschool_client_id'] %>
  smartschool_client_secret: <%= SECRET_KEYS['smartschool_client_secret'] %>
  office365_client_id: <%= SECRET_KEYS['office365_client_id'] %>
  office365_client_secret: <%= SECRET_KEYS['office365_client_secret'] %>
  google_client_id: <%= SECRET_KEYS['google_client_id'] %>
  google_client_secret: <%= SECRET_KEYS['google_client_secret'] %>
  recaptcha_site_key: <%= SECRET_KEYS['recaptcha_site_key'] %>
  recaptcha_secret_key: <%= SECRET_KEYS['recaptcha_secret_key'] %>

test:
  secret_key_base: 2f7d87fb78e082db53dee26230517b5c8b74642f4afc4e4df4b86767c4b68a330f36e1e706270d18c49fc2ecaee5ddeb006c027c744be52e0e2e63ccc0fa5386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= SECRET_KEYS['secret_key_base'] %>
  smartschool_client_id: <%= SECRET_KEYS['smartschool_client_id'] %>
  smartschool_client_secret: <%= SECRET_KEYS['smartschool_client_secret'] %>
  office365_client_id: <%= SECRET_KEYS['office365_client_id'] %>
  office365_client_secret: <%= SECRET_KEYS['office365_client_secret'] %>
  google_client_id: <%= SECRET_KEYS['google_client_id'] %>
  google_client_secret: <%= SECRET_KEYS['google_client_secret'] %>
  recaptcha_site_key: <%= SECRET_KEYS['recaptcha_site_key'] %>
  recaptcha_secret_key: <%= SECRET_KEYS['recaptcha_secret_key'] %>
