name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
      - develop

jobs:
  update_draft_release:
    name: Update Draft Release
    runs-on: ubuntu-latest
    steps:
      # Drafts next release notes as Pull Requests are merged into "develop"
      - uses: toolmantim/release-drafter@v5.17.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
